Absolute imports and module path alias
kawalcovid19/wargabantuwarga.com pull request #226
Opened 2021-07-20 14:50 UTC by faizrktm

Closes https://github.com/kawalcovid19/wargabantuwarga.com/issues/225

## Description

Configure tsconfig.json for module path alias for these paths. 
Nextjs and eslint uses tsconfig, might need to update other utilities such as test runner later when it exists to support the path alias.

Alias | Module
-- | --
`@components` | ./components/*
`@lib` | ./lib/*
`@styles` | ./styles/*
`@data` | ./data/*

## Current Tasks

- [ ] configure tsconfig 
- [ ] update current path references

2021-07-21 02:47 UTC, resir014 requested changes
Can we use `~/` instead? e.g. `~/components`.

2021-07-21 13:03 UTC, mazipan commented
Why I personally also support `~` instead of `@` as an alias is because of current situation where we face many libraries published under the scope which is using `@`.

So it become weird, if we can not differentiate our internal code vs the code from 3rd parties.

2021-07-21 13:16 UTC, faizrktm commented
yes agree, I also found the format clash with the current installed 3rd party lib `@heroicons`. It's updated! thanks, folks.

btw should we define for each module like `"~/components/*": "./components/*";` to handle possible folder structure changes in the future so we can migrate slowly and safely by only change alias instead of actual import statement.

or we can just `"~/*": "./*"` and agree structure will never change or be willing to change all import statements that changed.

2021-07-21 13:29 UTC, mazipan commented
If we learn from the framework approach like Vue CLI, it will come with the default alias ONLY for the root.

So instead of define many alias like

```json
{
  "~/*": "./*",
  "~components/*": "./components/*",
  "~pages/*": "./pages/*",
  "~assets/*": "./assets/*"
}
```

They choose to only define one alias for the root.

```json
{
  "~/*": "./*"
}
```

2021-07-21 13:33 UTC, mazipan approved these changes
Looks good for me ✅

2021-07-21 13:38 UTC, faizrktm commented
```
Also, you don't need to change all the import on this PR.
Better to do incremental changes.
Let the author update their implementation step by step.
```

well, it's done 😆 since no build is failing, I think it's safe for current changes to be merged ya?

2021-07-21 13:41 UTC, resir014 approved these changes
Yep, all good from me too!

2021-07-21 13:43 UTC, merged

2021-07-21 13:47 UTC, faizrktm commented
Thanks gengs!

2021-07-23 00:08 UTC, zainfathoni commented
@all-contributors please add @faizrktm for code and tools.