Add scroll to top functionality
kawalcovid19/wargabantuwarga.com pull request #280
Opened 2021-07-21 16:21 UTC by kevinmingtarja

Closes #254

## Description

Created a new ScrollArrow component. Open to suggestions on where it is best to place this button (**Will also improve the stylings soon :)** )

Desktop view:
<img width="1550" alt="Screen Shot 2021-07-22 at 00 17 01" src="https://user-images.githubusercontent.com/69668484/126523442-f2597e7c-90dc-4c0e-8dd9-b69e041d8016.png">

Mobile view:
<img width="612" alt="Screen Shot 2021-07-22 at 00 17 07" src="https://user-images.githubusercontent.com/69668484/126523482-d83528a2-098f-495a-ac4b-1ac223e6b460.png">

## Current Tasks

- [X] add button component to bring user to the top of page
- [ ] add the component to the pages that needs it

2021-07-21 16:38 UTC, resir014 requested changes
My main issue only relates to a11y right now. Other stuff are just nitpicks.

2021-07-21 16:38 UTC, resir014 commented on components/ui/scroll-arrow.tsx
> +    />
Please wrap this inside a `<button>`. Don't use `onClick` on non-interactable components.

2021-07-21 16:38 UTC, resir014 commented on components/ui/scroll-arrow.tsx
> +    const heightThreshold = 400;
Nitpick: We could make this changeable with a prop, I think.

2021-07-21 16:38 UTC, resir014 commented on components/ui/scroll-arrow.tsx
> +import React, { useCallback, useEffect, useState } from "react";
```suggestion
import { useCallback, useEffect, useState } from "react";
```

Nitpick: We no longer need to import `React` if we already imported another function.

2021-07-21 16:43 UTC, andriawan commented
Do we need seperate issue for implementing a11y @resir014 ? It think it needs more attention related to a11y

2021-07-21 17:12 UTC, resir014 commented
@andriawan For now we can just focus on making this a proper button. Any further a11y improvements can be made on a different issue.

@kevinmingtarja You can use the circular button example as provided in [Tailwind UI](https://tailwindui.com/components/application-ui/elements/buttons#component-6702d62917fd70644340f4008b126943).

2021-07-22 04:57 UTC, resir014 requested changes
Small design pass for the button. Used the [Tailwind UI circular button](https://tailwindui.com/components/application-ui/elements/buttons#component-6702d62917fd70644340f4008b126943) for this.

2021-07-22 04:57 UTC, resir014 commented on components/ui/scroll-arrow.tsx
> +    </button>
```suggestion
    <button
      className={clsx(
        showScroll ? "inline-flex" : "hidden",
        "items-center p-2 border border-transparent rounded-full shadow-sm text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500"
      )}
      onClick={scrollTop}
    >
      <ArrowUpIcon
        className={"h-5 w-5"}
      />
    </button>
```

2021-07-22 04:57 UTC, resir014 commented on components/ui/scroll-arrow.tsx
> +import { ArrowCircleUpIcon } from "@heroicons/react/solid";
```suggestion
import { ArrowUpIcon } from "@heroicons/react/outline";
```

2021-07-22 06:54 UTC, ekamuktia commented
How about adding the component on `LayoutRoot` instead? This way you don't need to add it on  every page
Is there any page that doesn't need scroll to top button?

2021-07-22 07:24 UTC, andriawan commented
good idea @ekamuktia. it will reduce repetition. and might be we can add config/props to exclude page which doesn't need the button.

2021-07-22 07:32 UTC, resir014 commented
Yep, let's go with this. Please make the necessary changes @kevinmingtarja.

2021-07-22 08:12 UTC, kevinmingtarja commented
> good idea @ekamuktia. it will reduce repetition. Might be we can add config/props to exclude page which doesn't need the button.

In order to be able to exclude some pages, should we add the component in `_app.tsx` instead? So that we can access the router props.

2021-07-22 10:33 UTC, resir014 approved these changes
🚢

2021-07-22 10:59 UTC, merged