Add/design system alert
kawalcovid19/wargabantuwarga.com pull request #363
Opened 2021-07-23 14:42 UTC by hanihusam

Closes #214 

## Description

Create reusable Alert component

2021-07-26 13:17 UTC, hanihusam commented
Mas @resir014 @zainfathoni I think we need global types for colors type and props. It is required by badge and alert. Wdyt?

2021-07-26 14:20 UTC, resir014 commented
@hanihusam Yes, let's go with that.

2021-07-27 19:17 UTC, resir014 commented
Can we also replace the alert in the homepage with this new alert, so we can see what it's like? @hanihusam 

![image](https://user-images.githubusercontent.com/5663877/127214498-96694a74-7573-43dd-acb7-396048a62131.png)

2021-07-27 22:40 UTC, hanihusam commented
> Can we also replace the alert in the homepage with this new alert, so we can see what it's like? @hanihusam 
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/5663877/127214498-96694a74-7573-43dd-acb7-396048a62131.png)
> 
> 

I think I already change it with the new one. Please kindly check it.

2021-07-27 23:28 UTC, zainfathoni requested changes

2021-07-27 23:28 UTC, zainfathoni commented on components/ui/alert/utils/helpers.ts
> +}
As you can see in the warning messages from Codecov above, you need to test this file either directly (by writing a unit test for this file) or indirectly (by writing an integration test for the home page where this file is eventually used). Please write the tests for your new components. You can look at some examples in the existing `*.test.ts` or `*.test.tsx` files. 😁 
Thanks!

2021-07-27 23:28 UTC, zainfathoni commented on pages/index.tsx
> +  <Alert accentBorder className={className} icon={ClockIcon}>
This line is also needs to be covered by your tests.

2021-07-28 00:30 UTC, zainfathoni commented on pages/index.tsx
> +  <Alert accentBorder className={className} icon={ClockIcon}>
I have added a test for the `HomePage`, but apparently it's not sufficient to test all the possibilities in the `helpers.ts` file. 😅

2021-07-28 05:20 UTC, resir014 submitted a review, later dismissed

2021-07-28 05:20 UTC, resir014 commented on components/ui/alert/alert.tsx
> +      "rounded-md p-4",
```suggestion
      "p-4",
```

I think we can live without `border-radius` from now on. The upcoming designs for Web 2.0 will be without rounded corners too, so let's follow the same design.

2021-07-28 05:20 UTC, resir014 commented on components/ui/alert/utils/types.ts
> +   * Set broder style in the left of component.`
```suggestion
   * Set border style in the left of component.`
```

typo 😅

2021-07-28 05:20 UTC, resir014 commented on components/ui/types.ts
> +export type Colors =
```suggestion
export type BaseColors =
```

Be more specific with the type naming.

2021-07-28 05:20 UTC, resir014 commented on package.json
> +    "react-transition-group": "^4.4.2",
```suggestion
    "react-transition-group": "^4.4.2",
```

Use `Transition` in [Headless UI](https://headlessui.dev/react/transition) instead.

2021-07-28 05:58 UTC, zainfathoni commented on components/ui/alert/utils/helpers.ts
> +}
I have added a unit test for the `helpers.ts` file.
Please update the tests accordingly when you're updating your implementations based on @resir014's comments.
Thanks!

2021-07-28 12:01 UTC, resir014 commented
@hanihusam also, when #487 is merged, we will have an additional colour, `light-blue`. When the time comes, please update this PR accordingly.

2021-07-31 02:09 UTC, zainfathoni approved these changes

2021-07-31 03:27 UTC, merged