refactor Page components, add Database page CTA
kawalcovid19/wargabantuwarga.com pull request #393
Opened 2021-07-25 02:52 UTC by resir014

Closes #391
Partial work for #333

## Description

Reworking how the Page components work to better implement the Website 2.0 designs, as well as initial steps for the homepage CTA boxes.

2021-07-25 10:40 UTC, zainfathoni requested changes
Overall, it looks good to me.

However, there's a missing piece that we need to implement along with this refactoring.
Without the #406 issue implemented, we cannot persist the information of the `Kebutuhan` that our users click. Hence there will be a missing gap in the user experience.

Please implement #406 within this PR as well, thanks, @resir014!

2021-07-25 11:41 UTC, resir014 commented
@zainfathoni Done. Need you help debugging the issue I told you earlier on DM.

2021-07-25 23:27 UTC, zainfathoni commented
Mbak @ekamuktia, could you please help us to fix this issue in this branch? You can try to reproduce it using the deployment preview link.
We can't merge this PR unless this issue is resolved, because we're risking our user experience here.

https://user-images.githubusercontent.com/6315466/126916739-b404c183-650c-4e91-99dd-82792feabb26.mov

2021-07-26 01:09 UTC, ekamuktia commented
@zainfathoni Please check #433

2021-07-26 11:09 UTC, zainfathoni requested changes

2021-07-26 11:09 UTC, zainfathoni commented on __tests__/pages/provinces/index.test.tsx
> +
Please remove this manual mock with `next-router-mock`, thanks!

2021-07-26 11:19 UTC, zainfathoni approved these changes
Approved with some minor notes. ✅

Thanks for working on it, @resir014! 🙏

2021-07-26 11:19 UTC, zainfathoni commented on components/home/__tests__/homepage-start.test.tsx
> +});
If we want to keep this snapshot test once we migrate the content to Netlify CMS, we need to remember to mock the values, not relying on the `_content` directory which can be changed by our editors.

2021-07-26 11:19 UTC, zainfathoni commented on __tests__/pages/provinces/index.test.tsx
> +}));
Is replacing this with `next-router-mock` breaking your test?
If not, please replace it, so we don't need to maintain the mocking code too much. 😁

2021-07-26 11:28 UTC, zainfathoni approved these changes
LGTM 💯

2021-07-26 11:47 UTC, merged