feat(cms): netlify CMS configs for About page
kawalcovid19/wargabantuwarga.com pull request #616
Opened 2021-08-09 14:05 UTC by mazipan

Closes #326

## Description

Tentang kami Page

## Current Tasks

- [ ] Netlify CMS config for content body
- [ ] Netlify CMS config for list of videos
- [ ] Netlify CMS config for list of contributors
- [ ] Slicing UI for About Page
- [ ] Read the data
- [ ] Testing

2021-08-09 14:33 UTC, mazipan commented
Who's have access to upload image to cloudinary ya @resir014 @zainfathoni?

2021-08-09 14:36 UTC, mazipan commented
Need upload this:

About Page -- Main Image
![gratis-sembako-ini-digantung-untuk-bantu-warga-terdampak-covid-19_169 1(1)](https://user-images.githubusercontent.com/7221389/128723750-85eeba33-e7fc-48c3-bcac-bec153de705b.png)

About Page -- Video Thumbnail 1

![download (22) 1](https://user-images.githubusercontent.com/7221389/128723954-c3281899-8ef1-45cd-a942-48fcabb53b43.png)

About Page -- Video Thumbnail 2

![download (21) 1](https://user-images.githubusercontent.com/7221389/128724036-e7a193ee-f27e-4439-a286-ede1b1260d29.png)

2021-08-09 15:02 UTC, mazipan commented
For temporary, I will use my own Cloudinary

2021-08-10 02:24 UTC, resir014 commented
Okay, I'll upload them.

2021-08-10 02:33 UTC, resir014 commented
@mazipan 

About Page -- Main Image

https://res.cloudinary.com/wargabantuwarga/image/upload/v1628562337/128723750-85eeba33-e7fc-48c3-bcac-bec153de705b_ptasae.png

About Page -- Video Thumbnail 1

https://res.cloudinary.com/wargabantuwarga/image/upload/v1628562409/128723954-c3281899-8ef1-45cd-a942-48fcabb53b43_joubqm.png

About Page -- Video Thumbnail 2

https://res.cloudinary.com/wargabantuwarga/image/upload/v1628562441/128724036-e7a193ee-f27e-4439-a286-ede1b1260d29_suos7t.png

About Page -- Logo KitaBisa

https://res.cloudinary.com/wargabantuwarga/image/upload/v1628562465/128724320-3102fa65-3d99-4ba6-b045-e819ffe0364f_rc0scp.png

About Page -- Logo KawalCovid

https://res.cloudinary.com/wargabantuwarga/image/upload/v1628562487/128724490-c64239c5-ab17-498b-8267-314515b942f0_lziid2.png

About Page -- Logo FIM

https://res.cloudinary.com/wargabantuwarga/image/upload/v1628562551/128724600-f7c60a95-9ab9-4761-bcbb-a25fa3596a1a_npxy45.png

About Page -- Logo FZ

https://res.cloudinary.com/wargabantuwarga/image/upload/v1628562569/128724687-994afef6-944b-4e00-ad2d-752bd63c0c6b_krjmjo.png

About Page -- Logo Kata.ai (new Kata.ai logo)

https://res.cloudinary.com/wargabantuwarga/image/upload/v1628562739/kata-horizontal-blue_kjhwrf.png

About Page -- Logo IndoRelawan

https://res.cloudinary.com/wargabantuwarga/image/upload/v1628562784/128724925-ce9d18c2-6bd3-45ae-9311-c5bf0868bd82_thi3pq.png

About Page -- Logo Pemimpin.id

https://res.cloudinary.com/wargabantuwarga/image/upload/v1628562788/128725017-34897249-608b-4455-a24f-35468a6450bd_nqk3r8.png

2021-08-10 07:44 UTC, resir014 requested changes

2021-08-10 07:44 UTC, resir014 commented on pages/tentang-kami.tsx
> +                Terima kasih kepada para kolaborator inisiatif #WargaBantuWArga
```suggestion
                Terima kasih kepada para kolaborator inisiatif #WargaBantuWarga
```

2021-08-10 08:07 UTC, resir014 approved these changes

2021-08-10 08:29 UTC, merged

2021-08-10 09:17 UTC, mazipan commented
Wah, belum ta ubah pake Next/Imagec :-D