Contribution icon
kawalcovid19/wargabantuwarga.com pull request #643
Opened 2021-08-11 15:39 UTC by hariangr

Closes #642  

## Description

This pull request add a new icon to homepage (Kontribusi) with dynamic property (fill) and a test
![image](https://user-images.githubusercontent.com/18433715/129059883-ed7ea9c4-2959-4027-8ef2-4d63da51b889.png)

## Current Tasks

- [v] Add new icon on homepage
- [v] Add testing

2021-08-11 16:33 UTC, resir014 requested changes
Some code structure issues. Please look into them! @hariangr

2021-08-11 16:33 UTC, resir014 commented on lib/home/homepage-menus.tsx
> +import { ContributionIcon } from "~/components/ui/icons/contribution-icon";
```suggestion
  DonationIcon,
  ContributionIcon,
} from "~/components/ui/icons";
```

Please include this icon inside the grouped exports on the `~/components/ui/icons/index.ts` file.

2021-08-11 16:36 UTC, resir014 commented
We should also add an `external` option to the `HomepageMenuItem` interface, to make sure external links get properly handled when this option is set (e.g. `target="_blank"` and proper `rel` attributes).

I think we can do this on a separate PR. What do y'all think? @mazipan @zainfathoni

2021-08-12 10:26 UTC, mazipan approved these changes
Looks good to me

2021-08-12 10:37 UTC, merged