feat(CMS): supported apps by kemnkes
kawalcovid19/wargabantuwarga.com pull request #706
Opened 2021-08-13 15:01 UTC by mazipan

## Description

Add new collection for Application Supported by Kemenkes

2021-08-13 23:14 UTC, zainfathoni requested changes
Thanks, Mas @mazipan!
However, I have a minor nitpick here. 😁

2021-08-13 23:14 UTC, zainfathoni commented on public/admin/config.yml
> +        file: _content/official_supported_apps.json
```suggestion
      - name: officially_supported_apps
        label: Officially Supported Apps by Kemenkes
        file: _content/officially_supported_apps.json
```

Just a nitpick on its grammatical error. 😅 🙏

2021-08-16 04:47 UTC, mazipan commented on public/admin/config.yml
> +        file: _content/official_supported_apps.json
Done

2021-08-16 13:38 UTC, zainfathoni approved these changes
LGTM 💯 

Thanks for working on it, Mas @mazipan! 🙏

2021-08-16 13:47 UTC, merged